### ISSUE TITLE
published or pending options in blog

### ISSUE THREAD

**Issue by ghost** [Laralum/Blog#7]
Will it be possible to add the posted or pending options to an entry in the blog? I mean that for example a user publishes a note as pending for revision and then another user pass it to published once this revised the spelling and others

sera posible que se agreguen las opciones de publicado o pendiente a una entrada en el blog? quiero decir que por ejemplo un usuario publique una nota como pendiente para revision y despues otro usuario la pase a publicada una vez este revisada la ortografia y demas

**Comment by 24aitor** [comment]
Parece una buena idea! Lo haremos

**Comment by ghost** [comment]
y en cuanto tiempo crees que la haran? sera en poco o mucho tiempo?  de verdad me encanto su cms y si eso estuviera disponible lo usaria sin duda, deseo migrar mis sitios en laravel a su cms 🙏🏼

**Comment by ConsoleTVs** [comment]
No creo que tardemos mucho :)

**Comment by 24aitor** [comment]
Ya esta hecho!! :)
